[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
either="1.0"
llvm-sys = "211.0.0-rc1"
inkwell = { version = "0.7.0", features = ["llvm21-1"] }

[[bin]]
name = "compiler"
path = "src/main.rs"

[lib]
name = "compiler"
path = "src/lib.rs"